#!/usr/bin/env python3
# Convert the C host's THREE ceiling-cast LUTs into Neo Geo C-ROM tiles + a header.
#   LUT A (/tmp/ceillut.raw)  = the spawn (grey tech) ceiling, 4 phases
#   LUT B (/tmp/ceillut2.raw) = the dark-room ceiling, 4 phases
#   LUT C (/tmp/ceillut3.raw) = the SPOTTED LAMP panel (TLITE class), 2 phases, TINTABLE:
#       its 4 brightest palette entries live in reserved slots 12..15, and the cart uploads
#       white/red/amber recolours of just those entries to palette slots 8/9/10 -- one set
#       of tiles serves every lamp-ceiling room colour.
# A+B keep the original single-LUT 8-phase footprint, so no downstream tile bases shift;
# C appends after them (ramps regenerate via wad2c --ramps, which re-reads tile counts).
import struct, subprocess, os
import shutil as _sh, os as _os
_TILETOOL = _sh.which("tiletool.py") or "/opt/homebrew/bin/tiletool.py"  # PATH-resolved (ngdevkit), brew fallback
_BREWPY = ("/opt/homebrew/opt/python3/bin:") if _os.path.isdir("/opt/homebrew/opt/python3/bin") else ""
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
NG   = os.path.join(HERE, "..", "neogeo")
env = dict(os.environ); env["PATH"] = _BREWPY + env.get("PATH", "")

def build(rawp, palp, gifp, c1p, c2p):
    raw = open(rawp, "rb").read()
    w, h, na, nph = struct.unpack("iiii", raw[:16])
    px = raw[16:16 + w * h]
    pal = [tuple(map(int, l.split())) for l in open(palp) if l.strip()]
    img = Image.frombytes('P', (w, h), bytes(px))
    flat = [0, 0, 0]
    for (r, g, b) in pal: flat += [r, g, b]
    flat += [0, 0, 0] * (256 - 1 - len(pal))
    img.putpalette(flat)
    img.save(gifp, optimize=False)
    subprocess.run([_TILETOOL, "--sprite", "-c", gifp, "-o", c1p, c2p], check=True, env=env)
    return w, h, na, nph, pal

wA, hA, na, nph, palA = build("/tmp/ceillut.raw",  "/tmp/ceillut.pal",  "/tmp/ceillutA.gif", "/tmp/clA.c1", "/tmp/clA.c2")
wB, hB, naB, nphB, palB = build("/tmp/ceillut2.raw", "/tmp/ceillut2.pal", "/tmp/ceillutB.gif", "/tmp/clB.c1", "/tmp/clB.c2")
wC, hC, naC, nphC, palC = build("/tmp/ceillut3.raw", "/tmp/ceillut3.pal", "/tmp/ceillutC.gif", "/tmp/clC.c1", "/tmp/clC.c2")
open(os.path.join(NG, "ceillut.c1"), "wb").write(open("/tmp/clA.c1","rb").read() + open("/tmp/clB.c1","rb").read() + open("/tmp/clC.c1","rb").read())
open(os.path.join(NG, "ceillut.c2"), "wb").write(open("/tmp/clA.c2","rb").read() + open("/tmp/clB.c2","rb").read() + open("/tmp/clC.c2","rb").read())

def tiles(f): return os.path.getsize(os.path.join(NG, f)) // 64
TILE0 = 257 + tiles("textiles.c1") + tiles("floorlut.c1") + tiles("sprites.c1")
COLS, ROWS = wA // 16, 112 // 16

def ng16(r, g, b):
    r5, g5, b5 = r >> 3, g >> 3, b >> 3
    return ((r5 & 1) << 14) | ((g5 & 1) << 13) | ((b5 & 1) << 12) \
         | ((r5 >> 1) << 8) | ((g5 >> 1) << 4) | (b5 >> 1)
def mk16(pal):
    p = [0] + [ng16(*c) for c in pal]; return p + [0] * (16 - len(p))
pal16A, pal16B, pal16C = mk16(palA), mk16(palB), mk16(palC)

with open(os.path.join(NG, "ceillut.h"), "w") as f:
    f.write("/* generated by tools/ceillut.py -- THREE ceiling LUTs: A grey/B dark (%d angles x %d phases), C spotted-tintable (%d phases) */\n" % (na, nph, nphC))
    f.write("#define CEILLUT_TILE0 %d\n#define CEILLUT_COLS %d\n#define CEILLUT_ROWS %d\n#define CEILLUT_NA %d\n#define CEILLUT_NPHASE %d\n#define CEILLUT_NLUT 2\n#define CEILLUT3_NPHASE %d\n#define CEILLUT_NAL 24\n"
            % (TILE0, COLS, ROWS, na, nph, nphC))
    f.write("static const unsigned short CEILLUT_PAL16[16]={%s};\n" % ",".join(str(x) for x in pal16A))
    f.write("static const unsigned short CEILLUT2_PAL16[16]={%s};\n" % ",".join(str(x) for x in pal16B))
    f.write("static const unsigned short CEILLUT3_PAL16[16]={%s};\n" % ",".join(str(x) for x in pal16C))

print("ceillut: TILE0=%d A+B (4ph) + spotted C (%dph), %d C-ROM tiles total -> neogeo/ceillut.{c1,c2,h}"
      % (TILE0, nphC, tiles("ceillut.c1")))
