#!/usr/bin/env python3
"""COLORMAP-for-VSLICE (cheap floor/ceiling try): bake the floor/ceiling distance-fade bands using
DOOM's real COLORMAP light-diminish curve (incl. its hue character) instead of the runtime linear
RGB scale. Contained: only the LUT murk bands (slots 11/10/14 floor, 9/15 ceiling), gated by g_cmfog.

The source bases match init_palettes: floor = FLOORLUT_PAL16 * 11/16 (slot 13 "the shade you liked"),
ceiling = CEILLUT_PAL16 (slot 12 raw). We pick COLORMAP levels whose brightness ~matches the current
gentle 0.94/0.81/0.69 fade, so the A/B isolates the curve+hue, not just "darker".

Run from repo root:  python3 tools/fb_fogcm.py      (writes neogeo/fogcm.h; DOOM-derived -> gitignored)
"""
import re, struct, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NG = os.path.join(ROOT, "neogeo")
# colormap the RAW LUT palettes at the ABSOLUTE band darkness (one colormap step, no pre-darken
# compounding) -> a visible spread. Floor bands ~ the linear 0.69*{0.94,0.81,0.69}=0.65/0.56/0.48
# (slot 13 base stays linear 0.69). Ceiling bands ~ 0.94/0.81 of the raw ceiling.
LEVELS_FLOOR = [9, 13, 16]  # slots 11 / 10 / 14 (deep, shared with ceiling band 3)
LEVELS_CEIL = [2, 6]        # slots 9 / 15


def glump(name, wad=os.path.join(ROOT, "doom1.wad")):
    d = open(wad, "rb").read()
    _, n, off = struct.unpack("<4sii", d[:12])
    for i in range(n):
        o, s, nm = struct.unpack("<ii8s", d[off + i * 16:off + i * 16 + 16])
        if nm.rstrip(b"\x00").decode() == name:
            return d[o:o + s]
    raise KeyError(name)


pp = glump("PLAYPAL")
PAL = [(pp[i * 3], pp[i * 3 + 1], pp[i * 3 + 2]) for i in range(256)]   # 8-bit RGB
CM = glump("COLORMAP")                                                  # [34][256] index->index


def parse_pal16(path, name):
    t = open(path).read()
    m = re.search(name + r"\s*\[\s*16\s*\]\s*=\s*\{([^}]*)\}", t)
    return [int(x.strip(), 0) for x in m.group(1).split(",") if x.strip()]


FLOOR16 = parse_pal16(os.path.join(NG, "floorlut.h"), "FLOORLUT_PAL16")
CEIL16 = parse_pal16(os.path.join(NG, "ceillut.h"), "CEILLUT_PAL16")


def w_to_rgb8(w):                       # 4-bit RGB444 word (r<<8|g<<4|b) -> 8-bit rgb
    return (((w >> 8) & 0xF) * 17, ((w >> 4) & 0xF) * 17, (w & 0xF) * 17)


def rgb8_to_w(r, g, b):                 # 8-bit rgb -> 4-bit RGB444 word
    return ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4)


def nearest_pal(r, g, b):
    bi, bd = 0, 1 << 30
    for i, (pr, pg, pb) in enumerate(PAL):
        d = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
        if d < bd:
            bd, bi = d, i
    return bi


def cmap_word(w, level, prescale16=16):
    """RGB444 word -> (optionally *prescale/16) -> nearest PLAYPAL -> COLORMAP[level] -> RGB444 word."""
    r, g, b = w_to_rgb8(w)
    if prescale16 != 16:
        r = min(255, r * prescale16 // 16); g = min(255, g * prescale16 // 16); b = min(255, b * prescale16 // 16)
    idx = CM[level * 256 + nearest_pal(r, g, b)]
    return rgb8_to_w(*PAL[idx])


def emit(f, name, src16, levels, prescale16):
    f.write("static const unsigned short %s[%d][16] = {\n" % (name, len(levels)))
    for lv in levels:
        row = [0] + [cmap_word(src16[i], lv, prescale16) for i in range(1, 16)]   # idx0 transparent
        f.write("  {" + ",".join("0x%04X" % w for w in row) + "},  /* COLORMAP level %d */\n" % lv)
    f.write("};\n")


with open(os.path.join(NG, "fogcm.h"), "w") as f:
    f.write("/* GENERATED by tools/fb_fogcm.py -- COLORMAP floor/ceiling distance-fade bands.\n")
    f.write("   DOOM-derived (PLAYPAL+COLORMAP) -> gitignored, do NOT commit. */\n")
    emit(f, "FOG_FLOOR", FLOOR16, LEVELS_FLOOR, 16)   # raw FLOORLUT, one colormap step
    emit(f, "FOG_CEIL", CEIL16, LEVELS_CEIL, 16)      # raw CEILLUT, one colormap step

print("fogcm: FOG_FLOOR[%d] (lvls %s) + FOG_CEIL[%d] (lvls %s) -> neogeo/fogcm.h" %
      (len(LEVELS_FLOOR), LEVELS_FLOOR, len(LEVELS_CEIL), LEVELS_CEIL))
