#!/usr/bin/env python3
"""FB SPIKE baker: 15 SOLID 8x8 fix tiles + the global palette, emitted for the cart.

Neo Geo gotcha: palette index 0 is HW-transparent on the fix layer (the gun relies on it).
So the framebuffer packs the 128-colour global palette as 15 colours/group at indices 1..15
(index 0 unused) across 8 fix palette slots -> needs 15 solid tiles, tile j = uniform index j+1.
A solid tile is swizzle-independent: every one of its 32 bytes = (i | (i<<4)).

Tiles go at the END of the SROM1 fix chain (after gunhand) = the documented safe region,
so no TILE0 reshuffle. FB_SOLID_TILE_BASE = GUNHAND_BASE + GUNHAND_NTILES.

Run from repo root:  python3 tools/fb_solidtiles.py
Outputs (both DOOM-derived via the palette -> gitignored, do not commit):
  neogeo/fbsolid.fix  - 15 solid tiles (480 bytes)
  neogeo/fbsolid.h    - FB_SOLID_TILE_BASE + FB_PAL_N + FB_PAL[] (RGB444 words)
"""
import re, struct, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NG = os.path.join(ROOT, "neogeo")

# chain end: gunhand is the last .fix in the SROM1 chain (Makefile), so the next free tile is
# GUNHAND_BASE + GUNHAND_NTILES.
gh = open(os.path.join(NG, "gunhand.h")).read()
base = (int(re.search(r"GUNHAND_BASE\s+(\d+)", gh).group(1)) +
        int(re.search(r"GUNHAND_NTILES\s+(\d+)", gh).group(1)))

# 15 solid tiles, tile j (0..14) = uniform 8x8 of palette index (j+1)
fix = bytearray()
for j in range(15):
    i = j + 1
    fix += bytes([(i | (i << 4)) & 0xFF]) * 32
open(os.path.join(NG, "fbsolid.fix"), "wb").write(fix)

# global palette + COLORMAP->global LUT from the dist/palette128 groundwork artifact. That artifact is
# DOOM-derived (PLAYPAL/COLORMAP) and lives OUTSIDE the public rom-vs pipeline, so a fresh checkout / clean
# export may not have it. The FB framebuffer (param 47 'fb') is a gated-OFF debug spike, so when the
# artifact is absent we emit a compile-only STUB (zeroed palette + colormap, at the real dims) -> the cart
# still builds and the live VSLICE engine is unaffected. Drop dist/palette128/*.bin back in and re-run for
# the genuine table.
PALBIN = os.path.join(ROOT, "dist/palette128/palette_global.bin")
CMBIN  = os.path.join(ROOT, "dist/palette128/colormap_global.bin")
STUB = not (os.path.exists(PALBIN) and os.path.exists(CMBIN))
if STUB:
    N, NLEV = 119, 34                      # real dims: 119-colour global palette x 34 COLORMAP levels
    pal = [0] * N
    cm = bytes(N * NLEV)
else:
    pb = open(PALBIN, "rb").read()
    pal = [struct.unpack_from("<H", pb, i)[0] for i in range(0, len(pb), 2)]
    N = len(pal)
    cm = open(CMBIN, "rb").read()          # COLORMAP -> global LUT: [levels][N] global-index -> darkened global-index
    NLEV = len(cm) // N

with open(os.path.join(NG, "fbsolid.h"), "w") as f:
    f.write("/* GENERATED by tools/fb_solidtiles.py -- FB spike solid tiles + global palette.\n")
    f.write("   15 solid fix tiles at FB_SOLID_TILE_BASE (chain end); tile j = palette index j+1\n")
    f.write("   (index 0 is HW-transparent). FB_PAL[] = %d RGB444 words.\n" % N)
    f.write("   %s */\n" % ("STUB: dist/palette128 absent -> zeroed FB palette/colormap (FB spike gated off; cart still builds)."
                            if STUB else "DOOM-derived (palette from PLAYPAL) -> gitignored, do NOT commit."))
    f.write("#define FB_SOLID_TILE_BASE %d\n" % base)
    f.write("#define FB_SOLID_NTILES 15\n")
    f.write("#define FB_PAL_N %d\n" % N)
    f.write("static const unsigned short FB_PAL[FB_PAL_N] = {\n")
    for k in range(0, N, 12):
        f.write("  " + ",".join("0x%04X" % w for w in pal[k:k + 12]) + ",\n")
    f.write("};\n")
    f.write("/* FB depth fog: PAL_COLORMAP[level][g] = darkened global index for global colour g at\n")
    f.write("   light level (0=bright .. 31=dark, 32=invuln, 33=black). DOOM's COLORMAP -> global. */\n")
    f.write("#define FB_COLORMAP_LEVELS %d\n" % NLEV)
    f.write("static const unsigned char PAL_COLORMAP[FB_COLORMAP_LEVELS][FB_PAL_N] = {\n")
    for m in range(NLEV):
        row = cm[m * N:(m + 1) * N]
        f.write("  {" + ",".join("%d" % b for b in row) + "},\n")
    f.write("};\n")

print("fbsolid: 15 solid tiles -> fbsolid.fix (%dB)  base=%d  FB_PAL_N=%d  COLORMAP %d lvls -> fbsolid.h%s" %
      (len(fix), base, N, NLEV, "  [STUB: no dist/palette128, zeroed]" if STUB else ""))
