#!/usr/bin/env python3
# Convert the C host's floor-cast LUT (/tmp/floorlut.raw + .pal) into Neo Geo
# C-ROM tiles + a header. Reuses the same tiletool path as the texture pipeline.
import struct, subprocess, os, sys
import shutil as _sh, os as _os
_TILETOOL = _sh.which("tiletool.py") or "/opt/homebrew/bin/tiletool.py"  # PATH-resolved (ngdevkit), brew fallback
_BREWPY = ("/opt/homebrew/opt/python3/bin:") if _os.path.isdir("/opt/homebrew/opt/python3/bin") else ""
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
NG   = os.path.join(HERE, "..", "neogeo")

raw = open("/tmp/floorlut.raw", "rb").read()
w, h, na, nph = struct.unpack("iiii", raw[:16])
px = raw[16:16 + w * h]
pal = [tuple(map(int, l.split())) for l in open("/tmp/floorlut.pal") if l.strip()]

img = Image.frombytes('P', (w, h), bytes(px))
flat = [0, 0, 0]                                   # index 0 = transparent/black
for (r, g, b) in pal: flat += [r, g, b]
flat += [0, 0, 0] * (256 - 1 - len(pal))
img.putpalette(flat)
gifp = "/tmp/floorlut.gif"; img.save(gifp, optimize=False)   # keep index 0 (PIL drops+shifts it -> floor goes transparent/black)

env = dict(os.environ); env["PATH"] = _BREWPY + env.get("PATH", "")
subprocess.run([_TILETOOL, "--sprite", "-c", gifp,
                "-o", os.path.join(NG, "floorlut.c1"), os.path.join(NG, "floorlut.c2")],
               check=True, env=env)

tex_tiles = os.path.getsize(os.path.join(NG, "textiles.c1")) // 64
TILE0 = 257 + tex_tiles                            # base(0-255)+placeholder(256)+textiles, then us
COLS, ROWS = w // 16, 112 // 16

def ng16(r, g, b):
    r5, g5, b5 = r >> 3, g >> 3, b >> 3
    return ((r5 & 1) << 14) | ((g5 & 1) << 13) | ((b5 & 1) << 12) \
         | ((r5 >> 1) << 8) | ((g5 >> 1) << 4) | (b5 >> 1)
pal16 = [0] + [ng16(*c) for c in pal]; pal16 += [0] * (16 - len(pal16))

with open(os.path.join(NG, "floorlut.h"), "w") as f:
    f.write("/* generated by tools/floorlut.py -- periodic floor-cast LUT (%d angles x %d phases) */\n" % (na, nph))
    f.write("#define FLOORLUT_TILE0 %d\n#define FLOORLUT_COLS %d\n#define FLOORLUT_ROWS %d\n#define FLOORLUT_NA %d\n#define FLOORLUT_NPHASE %d\n#define FLOORLUT_NAL 24\n"
            % (TILE0, COLS, ROWS, na, nph))   # NA = BAKED angles (13, half circle); NAL = logical headings (cart h-flips 13..23)
    f.write("static const unsigned short FLOORLUT_PAL16[16]={%s};\n" % ",".join(str(x) for x in pal16))

print("floorlut: TILE0=%d cols=%d rows=%d na=%d nphase=%d, %d C-ROM tiles -> neogeo/floorlut.{c1,c2,h}"
      % (TILE0, COLS, ROWS, na, nph, os.path.getsize(os.path.join(NG, "floorlut.c1")) // 64))
