#!/usr/bin/env python3
# Convert the live-engine HEX floor LUT (/tmp/vsfloor.raw + .pal) into Neo Geo C-ROM tiles, placed
# AFTER ramps (and BEFORE the trailing FF-only fftiles) so its offset is independent of the FF bake.
# The cart folds heading%VSFLOOR_NA (hex 60-degree symmetry). Separate from the shared floorlut (strip/FF).
import struct, subprocess, os
import shutil as _sh, os as _os
_TILETOOL = _sh.which("tiletool.py") or "/opt/homebrew/bin/tiletool.py"  # PATH-resolved (ngdevkit), brew fallback
_BREWPY = ("/opt/homebrew/opt/python3/bin:") if _os.path.isdir("/opt/homebrew/opt/python3/bin") else ""
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__)); NG = os.path.join(HERE, "..", "neogeo")
raw = open("/tmp/vsfloor.raw", "rb").read()
w, h, na, nph = struct.unpack("iiii", raw[:16])
px = raw[16:16 + w * h]
pal = [tuple(map(int, l.split())) for l in open("/tmp/vsfloor.pal") if l.strip()]
img = Image.frombytes('P', (w, h), bytes(px))
flat = [0, 0, 0]
for (r, g, b) in pal: flat += [r, g, b]
flat += [0, 0, 0] * (256 - 1 - len(pal))
img.putpalette(flat)
gifp = "/tmp/vsfloor.gif"; img.save(gifp, optimize=False)
env = dict(os.environ); env["PATH"] = _BREWPY + env.get("PATH", "")
subprocess.run([_TILETOOL, "--sprite", "-c", gifp,
                "-o", os.path.join(NG, "vsfloor.c1"), os.path.join(NG, "vsfloor.c2")], check=True, env=env)
# TILE0 = sum of the STATIC chain before vsfloor (logo..ramps). fftiles now TRAILS vsfloor/vsceil, so it
# is EXCLUDED here -- this is what makes the live floor offset independent of any FF re-bake.
def tiles(fn):
    p = os.path.join(NG, fn); return os.path.getsize(p)//64 if os.path.exists(p) else 0
TILE0 = (257   # base-crom-logo(256)+logo(1) -- HARDCODED: build/assets/*.c1 don't exist until the later cart-link step, so a FRESH build must NOT stat them (would read 0 -> TILE0 257 short -> spatially offset/wrapped floors). Matches wad2c.py FIRST_TEX_TILE / floorlut.py / ceillut.py.
         + tiles("textiles.c1") + tiles("floorlut.c1") + tiles("sprites.c1")
         + tiles("ceillut.c1") + tiles("ramps.c1"))
COLS, ROWS = w // 16, 112 // 16
def ng16(r, g, b):
    r5, g5, b5 = r >> 3, g >> 3, b >> 3
    return ((r5 & 1) << 14) | ((g5 & 1) << 13) | ((b5 & 1) << 12) | ((r5 >> 1) << 8) | ((g5 >> 1) << 4) | (b5 >> 1)
pal16 = [0] + [ng16(*c) for c in pal]; pal16 += [0] * (16 - len(pal16))
with open(os.path.join(NG, "vsfloor.h"), "w") as f:
    f.write("/* generated by tools/vsfloorlut.py -- live-engine HEX floor LUT (%d sets x %d phases, 60deg fold) */\n" % (na, nph))
    f.write("#define VSFLOOR_TILE0 %d\n#define VSFLOOR_COLS %d\n#define VSFLOOR_ROWS %d\n#define VSFLOOR_NA %d\n#define VSFLOOR_NPHASE %d\n"
            % (TILE0, COLS, ROWS, na, nph))
    f.write("static const unsigned short VSFLOOR_PAL16[16]={%s};\n" % ",".join(str(x) for x in pal16))
print("vsfloor: TILE0=%d cols=%d rows=%d na=%d nphase=%d, %d C-ROM tiles -> neogeo/vsfloor.{c1,c2,h}"
      % (TILE0, COLS, ROWS, na, nph, os.path.getsize(os.path.join(NG, "vsfloor.c1"))//64))
